### ISSUE TITLE
Create a resolver for the transription GraphQL query

### ISSUE THREAD

**Issue by aomi** [VikeLabs/lecshare-api#10]
Currently, a lot of the heavy lifting is done in the front-end. 

Allow the client to request only the transcription data it needs. 

Create a new resolver for this using the `transcription` query endpoint. 

This resolver, to be located in `graph/transcription.resolvers.go`, will read in a the `.json` transcription and return the data based on the query.

As this is a slightly involved, ticket, a few mile-stone steps are listed for guidance.

For now, open the `.json` file locally and have this working with the local GraphQL endpoint. Perhaps have this `.json` file reading working standalone before interfacing with the query resolver. Once than is implemented, report back to this issue.

**Comment by malcolmseyd** [comment]
See docs, it seems to work. `json.Unmarshal()` and `gqlgen` did everything pretty much automatically. 
https://documenter.getpostman.com/view/10174250/SzKYPGfW

**Comment by aomi** [comment]
Your resolver breaks when it is deployed on AWS by the way. Basically local files are finicky when deploying.
