### ISSUE TITLE
List Retrieval

### ISSUE THREAD

**Issue by ryleyw** [VikeLabs/lecshare-api#3]
For a given course name, API should give all lectures in the course

**Comment by malcolmseyd** [comment]
This already sort of works, as documented [here.](https://documenter.getpostman.com/view/10174250/SzKYPGfW) Should we consider closing this?

**Comment by malcolmseyd** [comment]
I updated the "classes" resolver to match the schema, you can now request a lecture's transcription as of commit: 64874cb95b700dddfef452982c6091147e2a685b
