### ISSUE TITLE
Make GraphQL schema for Google Speech to Text Transcription JSON

### ISSUE THREAD

**Issue by aomi** [VikeLabs/lecshare-api#6]
Make a GraphQL schema that matches the schema that the transcription file has.

Place this under a new schema file `graph/transcription.graphql`.

**Comment by malcolmseyd** [comment]
Done. See pull request #9

**Comment by aomi** [comment]
I feel bad, I didn't think of this before requesting this.

Basically there is a schema defined all all Google API stuff (most I think), which is called defined using the protobuf schema. The one for the speech if defined in this file.
https://github.com/googleapis/googleapis/blob/master/google/cloud/speech/v1/cloud_speech.proto

It looks like Google have already made a Protobuf to GraphQL thing....
https://rejoiner.io/
